language: node_js
sudo: false
branches:
  only:
  - master
git:
  depth: 1
node_js:
- '5'
before_script:
- chmod -R +x script
after_success:
- test $TRAVIS_BRANCH = "master" && script/deploy-gh-pages.sh
deploy:
  provider: npm
  email: me@platane.me
  api_key:
    secure: oRqWjCLcTGge7o0JHpsGTkYRoPglfQrbRCAoUc/njetVaBgUYHTTvPpd0PLjlYs0P1VxtsI4rV1xkkwhyb2QulknTTnH3uzswSdMwkrzovn/Y/4hsKL44VOllIGaAQaFPKH8WWUxGXLJHdewcqzqDFIOSJZRNQxZ4+KfXYd+p4H7yFNSO4+Gyz0h+qKmvoAuTsUpehaDZeZOzQCapj35dcMYi/jM9qnM+drwPXJC4KKe39VvWg/Q8odtSoAO12fRK+XaRG3IewE+C6UamqBg8E7XIl2ZJQlugEe0oAL3ewxS4xehSWWl6wWkEWNq7WU4vL7Chz7LhzKLg6L0geW43698zVXFrxrJYTepk9nCK9D8EQnUWye8xyBcuKc+Lz5mOTDvVsKkQ/VHNVSXSV6F3jf4oJFLIgNhGCCByrlKkyn6iawFkq94K69o9bTDCo6DVOQFVe527anhlXmBYm+q3pNj+ud/JVAKl41FVOAUvuah/SYrbnc/KuIMc12l3xAdSFrz3x2UhxextO008qkPgp4+HjdqsLZvm1gGolVjeSGQkosf5z0tYUffjZA0em44So+0K3FS/yD6Z7Wna+eGckM9runuprKK8oeu+kHPCPvc2qqDdHSCMgOT3I6PdTW8rKUu2LWEeXfv6eD4aNnD8+s3Tx+rmX5UJV5Vjg07yt4=
  on:
    repo: Platane/react-flippity
    branch: master
  skip_cleanup: true
